name: Build-and-Deploy-Azure-Function

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node (if Node runtime)  # adjust for Python/.NET
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build function (example for Node)
        working-directory: ./src/function
        run: npm install
      - name: Build
        working-directory: ./src/function
        run: npm run build || echo "no build step"
        
      - name: Zip function package
        working-directory: ./src/function
        run: |
          zip -r ../function-package.zip . 

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Terraform outputs (optional)
        # if Terraform ran in another job and produced state/artifacts, fetch outputs; otherwise hardcode names
        run: |
          # If you ran terraform in the same workflow previously, use terraform output
          # Example assumes terraform is available and run in terraform/ directory
          # AKS example: ADAPT: here we fetch the function name and RG from terraform outputs if present
          if [ -f terraform/terraform.tfstate ]; then
            FUNCTION_NAME=$(cd terraform && terraform output -raw demo-func-app)
            RG=$(cd terraform && terraform output -raw resource_group)
            echo "FUNCTION_NAME=demo-func-app" >> $GITHUB_ENV
            echo "RG=demo-func-rg" >> $GITHUB_ENV
          else
            echo "RG=demo-func-rg" >> $GITHUB_ENV
            echo "FUNCTION_NAME=demo-func-app" >> $GITHUB_ENV
          fi

      - name: Deploy zip to Function App
        run: |
          echo "Deploying demo-func-app in resource group $RG"
          az functionapp deployment source config-zip \
            --resource-group "demo-func-rg" \
            --name "demo-func-app" \
            --src function-package.zip
