name: Terraform Build-and-Deploy Azure Function

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node (for function deployment)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      # Step 4: Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          auth-type: service_principal

      # Step 5: Terraform init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # Step 6: Terraform plan (optional)
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      # Step 7: Terraform apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # Step 8: Get Terraform outputs (Function App and Resource Group)
      - name: Get Terraform outputs
        id: tfoutputs
        working-directory: terraform
        run: |
          FN=$(terraform output -raw function_name_name)
          RG=$(terraform output -raw resource_group)
          printf "FUNCTION_NAME=%s\n" "$FN" >> $GITHUB_ENV
          printf "RG=%s\n" "$RG" >> $GITHUB_ENV
          printf "function_name=%s\n" "$FN" >> $GITHUB_OUTPUT
          printf "resource_group=%s\n" "$RG" >> $GITHUB_OUTPUT

      # Step 9: Build Node project
      - name: Install dependencies
        working-directory: src/function
        run: npm install

      - name: Build function
        working-directory: src/function
        run: npm run build || echo "no build step"

      # Step 10: Zip function
      - name: Zip function package
        working-directory: src/function
        run: |
          ZIP_PATH="$GITHUB_WORKSPACE/function-package.zip"
          rm -f "$ZIP_PATH"
          zip -r "$ZIP_PATH" .
          echo "Created $ZIP_PATH"

      # Step 11: Deploy function
      - name: Deploy function
        run: |
         - name: Deploy Function App
  run: |
    echo "Deploying $FUNCTION_NAME to $RG"
    az functionapp deployment source config-zip \
      --resource-group "$RG" \
      --name "$FUNCTION_NAME" \
      --src "$GITHUB_WORKSPACE/function-package.zip"
      